KT Screen
Rajan1803/swift-basic-assignment pull request #14
Opened 2023-06-14 07:43 UTC by Rajan1803

Screens for food app

2023-06-14 08:58 UTC, purva-SS requested changes
- In FoodTableViewCell  if you are returning cgsize outside the switch case no need to take .none case use only either one 
-  RecommendationsClcVCell - setup views methods should be private 
- make all the outlets private
- DiscountClcVCell - components should be taken inside view 
- RecomendScreenTblVCell - trailing constraint of stack view missing
- In FoodAppScreenVC unnecessary print statement at line no 132 
- line 33 why to wrap UIViewController instead down cast RecommendationsScreenVC

2023-06-14 14:34 UTC, purva-SS commented on UIComponets/FoodAppScreen/CustomViews/TableViewSectionHeader.swift
> +    var delegate: LoadSecondVC?
declare weak delegates to avoid retain cycle

2023-06-14 14:36 UTC, purva-SS commented on UIComponets/InstagramProfileScreen/CustomView/InstaTableViewCell.swift
> +        self.clcViewPost.register(UINib(nibName: Constants.Nib.instaCollectionVCell, bundle: nil), forCellWithReuseIdentifier: Constants.Nib.instaCollectionVCell)
no need to add self

2023-06-14 14:37 UTC, purva-SS commented on UIComponets/InstagramProfileScreen/CustomView/TableViewHeader.swift
> +    @IBOutlet weak var imageContainer: UIView!
add private access modifiers while declaring outlets

2023-06-14 14:37 UTC, purva-SS commented on UIComponets/InstagramProfileScreen/ViewControllers/InstagramProfileVC.swift
> +        self.tblView.register(UINib(nibName: Constants.Cell.instaTableViewCell, bundle: nil), forCellReuseIdentifier: Constants.Cell.instaTableViewCell)
remove self

2023-06-14 14:54 UTC, purva-SS approved these changes

2023-06-15 06:26 UTC, Shilpriya-Simform requested changes

2023-06-15 06:26 UTC, Shilpriya-Simform commented on UIComponets/FoodAppScreen/CustomViews/DiscountSectionHeader.swift
> +    @IBOutlet private weak var containerView: UIView!
add mark

2023-06-15 06:26 UTC, Shilpriya-Simform commented on UIComponets/FoodAppScreen/CustomViews/DiscountSectionHeader.swift
> +    func setUpViews() {
add access specifier, self review in entire PR

2023-06-15 06:26 UTC, Shilpriya-Simform commented on UIComponets/FoodAppScreen/CustomViews/FoodTableHeader.swift
> +        [walletContainerView,payContainerView,topUpContainerView].forEach {
👍

2023-06-15 06:26 UTC, Shilpriya-Simform commented on UIComponets/FoodAppScreen/CustomViews/FoodTableViewCell.swift
> +        switch FoodSection(rawValue: currentSection) {
👍

2023-06-15 06:26 UTC, Shilpriya-Simform commented on UIComponets/FoodAppScreen/CustomViews/RecommendationsClcVCell.swift
> +
avoid unnecessary spaces and comments

2023-06-15 06:26 UTC, Shilpriya-Simform commented on UIComponets/FoodAppScreen/CustomViews/TableViewSectionHeader.swift
> +    func seeAllButtonClicked()
add Delegate in protocol name where it's use for Delegate, this name misinterpreted to view controller insted of protocol

2023-06-15 06:26 UTC, Shilpriya-Simform commented on UIComponets/FoodAppScreen/Model/EnumForRecomandedSections.swift
> +enum RecomandedSections: Int {
👍

2023-06-15 06:26 UTC, Shilpriya-Simform commented on UIComponets/FoodAppScreen/Model/EnumForSections.swift
> +enum FoodSection: Int {
👍

2023-06-15 06:26 UTC, Shilpriya-Simform commented on UIComponets/FoodAppScreen/ViewController/FoodAppScreenVC.swift
> +extension FoodAppScreenVC: LoadSecondVC {
add mark in extenstion

2023-07-19 15:41 UTC, merged