UIComponents
Rajan1803/swift-basic-assignment pull request #4
Opened 2023-05-10 16:33 UTC by Rajan1803

2023-05-11 10:54 UTC, SagarAjudiya reviewed
You need to check for Mark and Spacing for whole project and also make all outlets private if it's only used for that scope

2023-05-11 10:54 UTC, SagarAjudiya commented on AutoLayout/AutoLayout/AppDelegate.swift
> +    func application(_ application: UIApplication, didFinishLaunchingWithOptions launchOptions: [UIApplication.LaunchOptionsKey: Any]?) -> Bool {
Remove extra spaces and add mark

2023-05-11 10:54 UTC, SagarAjudiya commented on AutoLayout/AutoLayout/AppDelegate.swift
> +
Remove extra space only one space after class start and before class end

2023-05-11 10:54 UTC, SagarAjudiya commented on AutoLayout/AutoLayout/SceneDelegate.swift
> +    func scene(_ scene: UIScene, willConnectTo session: UISceneSession, options connectionOptions: UIScene.ConnectionOptions) {
Remove extra space and add mark

2023-05-11 10:54 UTC, SagarAjudiya commented on AutoLayout/AutoLayout/SceneDelegate.swift
> +
Extra space

2023-05-11 10:54 UTC, SagarAjudiya commented on AutoLayout/AutoLayout/ViewController.swift
> +
Add mark and remove spaces

2023-05-11 10:54 UTC, SagarAjudiya commented on Localize/Localize/AppDelegate.swift
> +    func application(_ application: UIApplication, didFinishLaunchingWithOptions launchOptions: [UIApplication.LaunchOptionsKey: Any]?) -> Bool {
Extra space and add mark

2023-05-11 10:54 UTC, SagarAjudiya commented on Localize/Localize/AppDelegate.swift
> +
Remove this

2023-05-11 10:54 UTC, SagarAjudiya commented on Localize/Localize/SceneDelegate.swift
> +
Remove this, add mark

2023-05-11 10:54 UTC, SagarAjudiya commented on Localize/Localize/SceneDelegate.swift
> +
Remove extra space

2023-05-11 10:54 UTC, SagarAjudiya commented on Localize/Localize/ViewController.swift
> +    @IBOutlet weak var label1: UILabel!
Add mark

2023-05-11 10:54 UTC, SagarAjudiya commented on Localize/Localize/ViewController.swift
> +
Extra Space

2023-05-11 10:54 UTC, SagarAjudiya commented on UIComponets/AppDelegate/AppDelegate.swift
> +
Extra space, add mark

2023-05-11 10:54 UTC, SagarAjudiya commented on UIComponets/AppDelegate/AppDelegate.swift
> +
Extra space

2023-05-11 10:54 UTC, SagarAjudiya commented on UIComponets/AppDelegate/SceneDelegate.swift
> +
Add mark

2023-05-11 10:54 UTC, SagarAjudiya commented on UIComponets/AppDelegate/SceneDelegate.swift
> +
Remove space

2023-05-11 10:54 UTC, SagarAjudiya commented on UIComponets/BaseViewController/BaseViewController.swift
> +    override func viewDidLoad() {
Mark add

2023-05-11 10:54 UTC, SagarAjudiya commented on UIComponets/Extensions/UISliderExtention.swift
> +    }
Mark

2023-05-11 10:54 UTC, SagarAjudiya commented on UIComponets/Extensions/UIImageViewExtension.swift
> +
Mark

2023-05-11 10:54 UTC, SagarAjudiya commented on UIComponets/Extensions/UIViewExtension.swift
> +        }
Add mark and check Tab spacing

2023-05-11 10:54 UTC, SagarAjudiya commented on UIComponets/Extensions/UIViewExtension.swift
> +}
Add mark and check spacing in whole project

2023-05-11 10:54 UTC, SagarAjudiya commented on UIComponets/Helper/Enumeration.swift
> +
Space???

2023-05-11 10:54 UTC, SagarAjudiya commented on UIComponets/Helper/PHPickerHelper.swift
> +    var imageView: UIImageView?
Add Space after class start

2023-05-11 10:54 UTC, SagarAjudiya commented on UIComponets/Helper/PHPickerHelper.swift
> +    func setPHPicker(viewController: UIViewController) {
Add mark for function

2023-05-11 10:54 UTC, SagarAjudiya commented on UIComponets/Helper/PHPickerHelper.swift
> +
Extra Space and Mark

2023-05-11 10:54 UTC, SagarAjudiya commented on UIComponets/Helper/AppConstants.swift
> +    struct Img {
give proper name

2023-05-11 10:54 UTC, SagarAjudiya commented on UIComponets/Helper/Validator.swift
> +    func isPincodeValid(pincode: String?) -> Bool {
- Add a mark for all function

2023-05-11 10:54 UTC, SagarAjudiya commented on UIComponets/ViewController/CustomButton.swift
> +
Space?

2023-05-11 10:54 UTC, SagarAjudiya commented on UIComponets/ViewController/ExtendFunctionsVC.swift
> +
Extra space???

2023-05-11 10:54 UTC, SagarAjudiya commented on UIComponets/ViewController/StylesInExtenstionsVC.swift
> +}
remove unnecessary comments

2023-05-11 10:54 UTC, SagarAjudiya commented on UIComponets/ViewController/TextFieldValidateVC.swift
> +        }
Can we optimize this code?

2023-05-11 10:54 UTC, SagarAjudiya commented on UIComponets/ViewController/TextFieldValidateVC.swift
> +            lblPincodeInvalid.isHidden = false
Same for this..

2023-05-11 10:54 UTC, SagarAjudiya commented on UIComponets/ViewController/TextFieldValidateVC.swift
> +    }
Can we optimize this?

2023-05-11 10:54 UTC, SagarAjudiya commented on UIComponets/ViewController/TextViewVC.swift
> +    override func viewDidLoad() {
mark for view life cycle

2023-05-11 10:54 UTC, SagarAjudiya commented on UIComponets/ViewController/UIButtonViewController.swift
> +
Make all outlet private if it's use in only that class

2023-05-11 10:54 UTC, SagarAjudiya commented on UIComponets/ViewController/UIPageControlVC.swift
> +    private func updatePageControl(){
Check Spacing

2023-05-11 10:54 UTC, SagarAjudiya commented on UIComponets/ViewController/UITextFieldVC.swift
> +}
??

2023-05-11 10:54 UTC, SagarAjudiya commented on UITextFieldValidate/UITextFieldValidate/AppDelegate.swift
> +
Remove Space & add mark

2023-05-11 10:54 UTC, SagarAjudiya commented on UITextFieldValidate/UITextFieldValidate/AppDelegate.swift
> +
Spacing

2023-05-11 10:54 UTC, SagarAjudiya commented on UITextFieldValidate/UITextFieldValidate/SceneDelegate.swift
> +
?

2023-05-11 10:54 UTC, SagarAjudiya commented on UITextFieldValidate/UITextFieldValidate/SceneDelegate.swift
> +
?

2023-05-11 10:54 UTC, SagarAjudiya commented on UITextFieldValidate/UITextFieldValidate/ViewController.swift
> +    override func viewDidLoad() {
Mark

2023-05-11 10:54 UTC, SagarAjudiya reviewed
You need to check for Mark and Spacing for whole project and also make all outlets private if it's only used for that scope

2023-05-12 07:28 UTC, Shilpriya-Simform requested changes

2023-05-12 07:28 UTC, Shilpriya-Simform commented on Localize/Localize/ViewController.swift
> +    @IBOutlet weak var label1: UILabel!
give meaningful name to variable and avoid numeric value in it, use prefix of UIElement such as lbl, txt

2023-05-12 07:28 UTC, Shilpriya-Simform commented on UIComponets/Helper/Enumeration.swift
> +enum LanguageSegmentTypes: Int {
all marks should define user of that scope not just enum, extenstion

2023-05-12 07:28 UTC, Shilpriya-Simform commented on UIComponets/Helper/Validator.swift
> +class Validator {
👍

2023-05-12 07:28 UTC, Shilpriya-Simform commented on UIComponets/UIComponetsTests/UIComponetsTests.swift
> +
remove test case files if we are not adding any test cases

2023-05-12 07:28 UTC, Shilpriya-Simform commented on UIComponets/ViewController/CustomButton.swift
> +  class CustomButton: UIView {
👍

2023-05-12 07:28 UTC, Shilpriya-Simform commented on UIComponets/ViewController/CustomButton.swift
> +        Bundle.main.loadNibNamed("CustomButton", owner: self)
Insted of static name "CustomButton" give name by self in string

2023-05-12 07:28 UTC, Shilpriya-Simform commented on UIComponets/ViewController/ExtendFunctionsVC.swift
> +class ExtendFunctionsVC: BaseViewController {
👍

2023-05-12 07:28 UTC, Shilpriya-Simform commented on UIComponets/ViewController/TextFieldValidateVC.swift
> +    @IBOutlet private var btnSubmit: UIButton!
why this outlet are not weak?, are'nt it will create strong reference

2023-05-12 07:28 UTC, Shilpriya-Simform commented on UIComponets/ViewController/TextViewVC.swift
> +        setPlaceholderInTextView(placeholderText: "Address", textfield: txtvAddress)
all the static text has to be in string file

2023-05-12 07:28 UTC, Shilpriya-Simform commented on UIComponets/ViewController/TextViewVC.swift
> +    // MARK: - FUNCTION
mark should be apply on group of function, we you want to add details on function then use document comment on function

2023-05-12 07:28 UTC, Shilpriya-Simform commented on UIComponets/ViewController/UIButtonViewController.swift
> +class UIButtonViewController: BaseViewController {
👍

2023-05-12 07:28 UTC, Shilpriya-Simform commented on UIComponets/ViewController/UITextFieldVC.swift
> +        txtEmail.delegate = self
avoid adding implementation directly in viewdidload instead create function for same

2023-05-12 07:28 UTC, Shilpriya-Simform commented on UIComponets/ViewController/UITextFieldVC.swift
> +            submitClick(btnSubmit)
avoid using tags for UIElements, tags are not feasible and readable on long run

2023-05-16 13:02 UTC, Shilpriya-Simform approved these changes
always self review PR, and avoid repeated issue such as spacing, naming conversion, reusability

2023-05-16 13:03 UTC, merged